### ISSUE TITLE
Remove predetermined options for GSC and networks

### ISSUE THREAD

**Issue by ChristopherMancuso** [krishnanlab/PyGenePlexus#143]
Right now if a user generates a GSC or network on there own and tries to run the code, it returns an error message like 

`ValueError: Unexpected GSC 'MyGSC', available choices are ['GO', 'DisGeNet']`

**Comment by RemyLau** [comment]
Yeah it's a good idea to add more flexibility in the GSC options to support custom GSCs.

However, we still need to have some explicit checks somewhere to make sure the input GSC is appropriate so that the errors are more easily trackable and fixable. To do that, I will need to update the GSC setter in GenePlexus class (see attached) by going through the data directory and check to see if all necessary files for the GSC is available there. If not, an exception will be raised to advice the preparation of missing files or list existing custom options if there's any. https://github.com/krishnanlab/PyGenePlexus/blob/02898907374a73969539b26c60efa4687a13bbe2/geneplexus/geneplexus.py#L157-L160

**Comment by ChristopherMancuso** [comment]
What do you mean by "all the necessary files"? I think just a single file needs to be there, and that is the GSC subset to the network. So wouldn't just checking for that given file be what the user would really need? The gsc.setter is set irrespective to the network, so would just checking if one file had the correct GSC?

Also, would a good solution be if they try to run on a custom GSC and they get the above error, could we give them a line to add to their script to add the GSC to the available choices? I guess this might not work for the CLI version though

**Comment by RemyLau** [comment]
Looked a bit further into it and there are a few more things to be taken into account

* The GSC setter can only check if `GSCOriginal_xxx.sjon` exists
* Somewhere down the line need to check GSC files specific to network: goodsets and universe.

**Comment by RemyLau** [comment]
I think a general issue is that currently there is simply no support for custom GSC

**Comment by RemyLau** [comment]
To improve the custom support (``net_type`` + ``gsc``), I will work on #146 first.

**Comment by ChristopherMancuso** [comment]
@RemyLau should we close this, based on #146 being closed?

**Comment by ChristopherMancuso** [comment]
I checked this out using custom networks and GSCs and it all is working great for me.
